name: CI

on:
  pull_request:
  push:
    # filtering branches here, prevents duplicate builds from pull_request and push
    branches:
      - main

  # early issue detection, run CI weekly on Sundays
  schedule:
    - cron: '0 6 * * 0'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node_version: ['12', '14']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: install dependencies
        run: npm install

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test
